---
title: "Saga Orchestration: Money Transfer Service"
---

sequenceDiagram
autonumber
participant OrderHistoryEventConsumer
participant OrderHistoryViewService
participant CustomerViewRepositoryCustom

OrderHistoryEventConsumer->> OrderHistoryEventConsumer: customerCreatedEventHandler()
OrderHistoryEventConsumer--> OrderHistoryViewService: createCustomer()
OrderHistoryViewService--> CustomerViewRepositoryCustom: addCustomer()
CustomerViewRepositoryCustom-->OrderHistoryViewService: return
OrderHistoryViewService-->OrderHistoryEventConsumer: return
OrderHistoryEventConsumer->>OrderHistoryEventConsumer: orderCreatedEventHandler()
OrderHistoryEventConsumer-->OrderHistoryViewService: addOrder()
OrderHistoryViewService-->CustomerViewRepositoryCustom: addOrder()
CustomerViewRepositoryCustom-->OrderHistoryViewService: return
OrderHistoryViewService-->OrderHistoryEventConsumer: return
OrderHistoryEventConsumer->>OrderHistoryEventConsumer: orderApprovedEventHandler()
OrderHistoryEventConsumer-->OrderHistoryViewService: approveOrder()
OrderHistoryViewService->>OrderHistoryViewService: updateOrderState()
OrderHistoryViewService-->CustomerViewRepositoryCustom: updateOrderState()
CustomerViewRepositoryCustom-->OrderHistoryViewService: return
OrderHistoryViewService--> OrderHistoryEventConsumer: return
OrderHistoryEventConsumer->>OrderHistoryEventConsumer: handleOrderCancelledEvent()
OrderHistoryEventConsumer-->OrderHistoryViewService: cancelOrder()
OrderHistoryViewService->>OrderHistoryViewService: updateOrderState()
OrderHistoryViewService-->CustomerViewRepositoryCustom: updateOrderState()
CustomerViewRepositoryCustom-->OrderHistoryViewService: return
OrderHistoryViewService-->OrderHistoryEventConsumer: return
